[package]
name = "opalkrnl"
version = "0.1.0"
edition = "2024"

[dependencies]
opal-kernel = { path = "../opal-kernel" }

[[bin]]
name = "opalkrnl"
path = "src/main.rs"
test = false
bench = false
harness = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

[profile.ktest-debug]
inherits = "dev"
panic = "abort"

[profile.ktest-release]
inherits = "release"
panic = "abort"
