#ifndef OPALSYS_FBCON_H
#define OPALSYS_FBCON_H

enum {
    FBCON_IOCTL_COLOR = 0,
    FBCON_IOCTL_GET_CURSOR = 1,
    FBCON_IOCTL_GOTOXY = 2,
    FBCON_IOCTL_SET_CURSOR_VISIBLE = 3,
    FBCON_IOCTL_PUT_AT = 4,
    FBCON_IOCTL_ERASE_LINE = 5,
    FBCON_IOCTL_SCROLL_UP = 6,
};

#endif
